### ISSUE TITLE
cargo check fails

### ISSUE THREAD

**Issue by bismitpanda** [kgrech/rust_arduino#1]
Hello, I cloned this repo and changed some files and run `cargo check` but getting errors.

`main.rs`
```rs
#![no_std]
#![no_main]

use arduino_hal::prelude::*;
use panic_halt as _;

#[arduino_hal::entry]
unsafe fn main() -> ! {
    loop { }
}
```

`arduino.yaml`
```yaml
arduino_home: "%LOCALAPPDATA%/Arduino15"
external_libraries_home: "%LOCALAPPDATA%/Arduino15/libraries"
core_version: 1.8.6
variant: eightanaloginputs
avr_gcc_version: 7.3.0-atmel3.6.1-arduino7
external_libraries:
arduino_libraries:
  - LiquidCrystal
definitions:
  ARDUINO: '10807'
  F_CPU: 16000000L
  ARDUINO_AVR_UNO: '1'
  ARDUINO_ARCH_AVR: '1'
flags:
  - '-mmcu=atmega328p'
bindgen_lists:
  allowlist_function:
    - LiquidCrystal.*
  allowlist_type:
    - LiquidCrystal.*
  blocklist_function:
    - Print.*
    - String.*
  blocklist_type:
    - Print.*
    - String.*

```
the error log is attatched below

**Note**: I used `LiquidCrystal.h` as it was installed in my ArduinoIDE and it did not have `Wire.h` as an include
[error.log](https://github.com/kgrech/rust_arduino/files/10817768/err.log)
